### ISSUE TITLE
Project does not load

### ISSUE THREAD

**Issue by torbenott** [JingyiGF/HERBS#16]
Saved project raised python error when trying to load. Unfortunately I wasn't able to reliably reproduce this. This is project using the Waxholm atlas and loading a single .tif slice, doing a single round of matching, and then trying to add a few probe locations in the atlas view. 

[Download link of project](https://www.dropbox.com/s/lzwtyyzv0jumggy/TQ02_SR_TQ02_deepest_Merging_Crop_001.pkl?dl=0)

```
Traceback (most recent call last):
  File "C:\Users\...\anaconda3\lib\site-packages\herbs\herbsgui.py", line 5487, in load_project_called
    p_dict = pickle.load(infile)
EOFError: Ran out of input
```

**Comment by rjp109** [comment]
Hello,

I am also having the same issue as this - some of the projects I load works but others give this 'ran out of input error'. Is there a solution?

Brilliant software otherwise!

**Comment by zoepearce** [comment]
Hello, 

I am also having this issue.  I had previously registered a .tif file to the Allen Atlas with a few labelled cell bodies. the project was saved but when attempting to open the project again, I get the error message shown below. 


```
EOFError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/HERBS/lib/python3.8/site-packages/herbs/herbsgui.py:5733, in HERBS.load_project_called(self)
   5731 try:
   5732     infile = open(project_path[0], 'rb')
-> 5733     p_dict = pickle.load(infile)
   5734     infile.close()
   5735 except (IOError, OSError, pickle.PickleError, pickle.UnpicklingError):

EOFError: Ran out of input
```

**Comment by JingyiGF** [comment]
Thank you all for the feedback! I answered @torbenott in other issues he opened that I noticed the problem. Will update the code next week. But I just realised that it is autumn holiday next week in Norway, I probably will have limited working hours. I will try my best to debug the problem, and try to fix it in 2 weeks. 

It will be great help for me If @rjp109 you could let me know what you did that the loaded project works and what did that the loaded project not work. I mean what kind of steps you did before saving the projects. Many thanks in advance.

**Comment by rjp109** [comment]
Hi @JingyiGF,

I'm afraid I can't identify any differences for what i did with the projects that load compared to the ones that don't (but the vast majority do not load). I am using herbs to identify probe location, so I load the atlas, load my image, use the triangulation to map the image onto the atlas, add the probe location, and then save the project. I also can't load objects that i have saved either, i get the same error.

Help with this would be much appreciated,

Thanks,
Ross

**Comment by JingyiGF** [comment]
Thank you all for the feedback and updates last week. I just update the code on GitHub and PyPI and hopefully this fixed the problem about loading a project and objects. Let me know if something went wrong. Many thanks!

**Comment by rjp109** [comment]
Hello,

Unfortunately it is still not working for me. Now I get a different error:

Traceback (most recent call last):
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\herbsgui.py", line 4726, in load_objects
    object_dict, msg = check_loading_pickle_file(object_file_path[0][i])
ValueError: too many values to unpack (expected 2)

I'm running HERBS on PyCharm.

**Comment by rjp109** [comment]
or this error for loading a project:

Traceback (most recent call last):
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\herbsgui.py", line 5390, in load_project_called
    p_dict, msg = check_loading_pickle_file(project_path[0])
ValueError: too many values to unpack (expected 2)

**Comment by JingyiGF** [comment]
did you load the saved projects or objects? if so, it will not work. as the problem before when you can load. projects or objects was not actually loading problem. it was actually a saving problem. I saved some thing that can not be pickled.
Could you please try to save new objects and projects and load?

**Comment by rjp109** [comment]
Ah ok, I was trying to load previously saved projects. I guess I will need to re-do and re-save my projects then. 
Thank you for the help.

**Comment by JingyiGF** [comment]
sorry for the inconvenience. I hope I fixed the problem this time. let me know if something went wrong. and looking forward to your feedback :-)

**Comment by rjp109** [comment]
Hello,
I can load the project fine now thank you. However I am now having a new issue when trying to merge probe parts. I typically load an image, map to atlas, add probe part, save. Then load next image, repeat. But when i try to merge the parts i get the following error (which i was not getting before):

Traceback (most recent call last):
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\herbsgui.py", line 4193, in merge_probes
    info_dict = calculate_probe_info(data[i], label_data, self.atlas_view.label_info,
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 402, in calculate_probe_info
    new_sp = correct_start_pnt(label_data, start_pnt, start_vox, direction)
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 162, in correct_start_pnt
    return new_sp
UnboundLocalError: local variable 'new_sp' referenced before assignment

**Comment by rjp109** [comment]
Another more minor point, when loading a project, i can no longer get the atlas overlay to show up over the image, regardless of composition selected or opacity used.

**Comment by abrahamzv** [comment]
> Hello, I can load the project fine now thank you. However I am now having a new issue when trying to merge probe parts. I typically load an image, map to atlas, add probe part, save. Then load next image, repeat. But when i try to merge the parts i get the following error (which i was not getting before):
> 
> Traceback (most recent call last): File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\herbsgui.py", line 4193, in merge_probes info_dict = calculate_probe_info(data[i], label_data, self.atlas_view.label_info, File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 402, in calculate_probe_info new_sp = correct_start_pnt(label_data, start_pnt, start_vox, direction) File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 162, in correct_start_pnt return new_sp UnboundLocalError: local variable 'new_sp' referenced before assignment

I also encounter this error in version 19. Works fine in version 18.

**Comment by JingyiGF** [comment]
Thank you all for the updates. Yup, I have checked the code, and found I for some reason changed the order of the code at some point. This can happen when the start point is very close to the boundary. You must be very lucky and did very nice job :-)

I rewrote the code for this part this morning and updated on GitHub. will update on PyPI later today. Trying to finish the code for user defined atlas while sick kiddo next to me at home now. Will update you when I upload to PyPI.

Also fixed the atlas boundary problem. The boundary layer was lower than overlay layer. so if you decreased the opacity for the overlay, you would see the boundary. Now I put the boundary layer above to the overlay layer, so you can see boundary without changing opacity.

Thanks for the update and feedback again 😊

**Comment by JingyiGF** [comment]
Update the code on PyPI now with the user defined atlas processor and tutorial. Let me know if it works fine :-)

**Comment by rjp109** [comment]
Hi,

Sorry to bother again, This works for some of my probes, but for others I'm still getting an error when trying to merge probe pieces:

Traceback (most recent call last):
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\herbsgui.py", line 4193, in merge_probes
    info_dict = calculate_probe_info(data[i], label_data, self.atlas_view.label_info,
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 473, in calculate_probe_info
    left_merged_labels, left_merged_colors, left_block_count = block_same_label_one_side(
  File "C:\Users\rp17047\PycharmProjects\pythonProject\venv\lib\site-packages\herbs\uuuuuu.py", line 371, in block_same_label_one_side
    merged_labels = [sites_label_one_side[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by JingyiGF** [comment]
Hi @rjp109, thank you for your feedback. this is an error from another function, I am really curious where you put the probe. Could you please paste a screen shot of the probe? and which atlas are you using?

**Comment by rjp109** [comment]
Hello,

Images attached. I am trying to merge a probe spanning two sections in the prefrontal area using the waxholm space rat atlas V4
![probepiece2](https://user-images.githubusercontent.com/34347005/197199235-d67fd116-54c7-4570-8d60-9cc785733650.PNG)
![probepiece1](https://user-images.githubusercontent.com/34347005/197199262-fe701aa6-a5f4-413c-aa3e-e45aade4c393.PNG)

**Comment by JingyiGF** [comment]
can you also list the page number? So I can reproduce the same error to check? Many thanks for the figures!

**Comment by rjp109** [comment]
Yep, its 716 and 727.

**Comment by rjp109** [comment]
I wonder if it is because it is limited to only two sections which may be too far apart, so it struggles to create a linear trajectory of the probe when merging..?

**Comment by JingyiGF** [comment]
I can re-produce the same error. Will fix it and come back to you later today.

**Comment by JingyiGF** [comment]
code update on GitHub, I will update on PyPI next week.

**Comment by rjp109** [comment]
Great, thank you very much for your help and quick response!

**Comment by vncntprvst** [comment]
Hi, I'm having an issue loading a saved project as well, so I'm posting it here but let me know if I should open a separate issue. 
This occurs with HERBS installed from the Github code, updated yesterday (October 24).
Here's the error output: 
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File D:\Code\HERBS\herbs\herbsgui.py:5407, in HERBS.load_project_called(self)
   5402         self.delete_all_atlas_layer()
   5404     # if self.image_view.image_file is not None:
   5405     #     self.delete_all
-> 5407     self.load_project(p_dict)
   5409 else:
   5410     self.print_message('', self.normal_color)

File D:\Code\HERBS\herbs\herbsgui.py:5183, in HERBS.load_project(self, p_dict)
   5181 if self.current_atlas == 'volume':
   5182     if self.current_atlas_path is not None:
-> 5183         self.load_volume_atlas(self.current_atlas_path)
   5185     self.atlas_display = atlas_ctrl_data['atlas_display']
   5187     if self.atlas_display == 'coronal':

File D:\Code\HERBS\herbs\herbsgui.py:4603, in HERBS.load_volume_atlas(self, atlas_folder)
   4599 boundary = {'s_contour': s_boundary, 'c_contour': c_boundary, 'h_contour': h_boundary}
   4601 self.set_volume_atlas_to_view(atlas_data, segmentation_data, atlas_info, label_info, boundary)
-> 4603 self.set_volume_atlas_3d(unique_label, meshdata, small_meshdata_list)

File D:\Code\HERBS\herbs\herbsgui.py:4517, in HERBS.set_volume_atlas_3d(self, unique_label, meshdata, small_meshdata_list)
   4515 if id in self.atlas_view.label_info['index']:
   4516     color_to_set = self.atlas_view.label_info['color'][(self.atlas_view.label_info['index'] == id)][0] / 255
-> 4517     mesh = gl.GLMeshItem(meshdata=small_meshdata_list[str(id)], smooth=True,
   4518                          color=(color_to_set[0], color_to_set[1], color_to_set[2], 0.8), shader='balloon')
   4519     mesh.setGLOptions('opaque')
   4520     mesh.translate(-mesh_origin[0], -mesh_origin[1], -mesh_origin[2])

KeyError: '545'
```
Thanks

**Comment by JingyiGF** [comment]
Hi @vncntprvst , thank you for the feedback and very clear error trace. I wonder if you download and process the atlas using the new code? Or the atlas was processed some time ago? brain region with label id '545' covers only 2 voxels, which can not merge to a 3d mesh object. If you processed the atlas some time ago, could you please re-download and re-process the atlas and try again? If you processed the atlas using the new code, I will have a closer look at it. Thanks.

**Comment by vncntprvst** [comment]
Hi Jingyi. 
The atlas was processed with an older version of the code. I'll download and re-process the atlas and let you know how it goes.
Thanks.

**Comment by vncntprvst** [comment]
It does work now. Thanks for the help!
