### ISSUE TITLE
Error when "merging" a single piece of a drawing

### ISSUE THREAD

**Issue by mwawra** [JingyiGF/HERBS#27]
During implementation of the unmerge stuff I found two errors.
When you try to "merge" a single drawing piece into a drawing the following error occurs:
`Traceback (most recent call last):
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\herbs\herbsgui.py", line 4316, in merge_drawings
    self.add_3d_object(info_dict, 'merged drawing')
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\herbs\herbsgui.py", line 4240, in add_3d_object
    obj_3d = make_3d_gl_widget(data_dict, obj_type)
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\herbs\obj_items.py", line 58, in make_3d_gl_widget
    obj_3d = create_drawing_line_in_3d(data_dict)
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\herbs\obj_items.py", line 32, in create_drawing_line_in_3d
    drawing_obj = gl.GLSurfacePlotItem(x=pos[:, 0], y=pos[:, 1], z=pos[:, 2], colors=vis_color)
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\pyqtgraph\opengl\items\GLSurfacePlotItem.py", line 31, in __init__
    self.setData(x, y, z, colors)
  File "C:\Users\Matthias\anaconda3\envs\conda_herbs\lib\site-packages\pyqtgraph\opengl\items\GLSurfacePlotItem.py", line 75, in setData
    if self._y is not None and z.shape[1] != len(self._y):
IndexError: tuple index out of range`

**Comment by JingyiGF** [comment]
thanks for the feedback. fixed on GitHub now. And thanks for the unmerging feature. I modified it a bit, so that when there are both merged object and pieces in the object control, the original merged button is only for merging, and data will not be saved twice :-)

**Comment by mwawra** [comment]
Thanks for the fix.
By the way, I like the unmerge button.

**Comment by JingyiGF** [comment]
this is a lazy fix. I was thinking to plot areas as cubes, but now I just use scatter instead. I will make a cube object later. affects only visualisation. The cells project fix is a bit annoying, I could not make the previous saved projects working for this version of code. I feel every time I changed the saving and loading projects/objects/layers code, the previous saved files can not work. I feel very sorry for the users but I am not sure how to fix this.
