### ISSUE TITLE
Error when merging probes 

### ISSUE THREAD

**Issue by nataliekoh** [JingyiGF/HERBS#36]
Hi, I am getting an error when trying to merge probe pieces (using recipe 6.6.2 in Cookbook with "tetrode"):

correct enter pnt with 11 steps
Traceback (most recent call last):
  File "C:\Users\---\AppData\Local\Continuum\anaconda3\envs\herbs\lib\site-packages\herbs\herbsgui.py", line 4277, in merge_probes
    info_dict, error_index = calculate_probe_info(data[i], label_data, self.atlas_view.label_info,
  File "C:\Users\---\AppData\Local\Continuum\anaconda3\envs\herbs\lib\site-packages\herbs\uuuuuu.py", line 552, in calculate_probe_info
    label_names, label_acronym, label_color, left_sites_color, right_sites_color = get_label_name(
  File "C:\Users\---\AppData\Local\Continuum\anaconda3\envs\herbs\lib\site-packages\herbs\uuuuuu.py", line 402, in get_label_name
    left_sites_color = np.zeros((len(sites_label), 3), 'i')
TypeError: object of type 'NoneType' has no len()

Not sure why this is happening - any help will be appreciated.

**Comment by nataliekoh** [comment]
I have not encountered this problem since updating to version 0.2.2. Will close this issue and re-open if it comes up again. Sorry!
