### ISSUE TITLE
Unable to process downloaded allen mice atlas

### ISSUE THREAD

**Issue by WenhaoLiu0218** [JingyiGF/HERBS#39]
![image](https://user-images.githubusercontent.com/36101333/228825186-0998d1ed-2aee-4e6f-aaa0-df39dc7a8351.png)
Thanks for developing this awesome tool. 
 I got an error when I press the "process"  button. 
Here is the error message, 
>>> herbs.run_herbs()
Traceback (most recent call last):
  File "C:\Users\Wenhao Liu\.conda\envs\herbs4\lib\site-packages\herbs\allen_downloader.py", line 93, in run
    vertices, faces = obj_data_to_mesh3d(filename)
  File "C:\Users\Wenhao Liu\.conda\envs\herbs4\lib\site-packages\herbs\uuuuuu.py", line 931, in obj_data_to_mesh3d
    face.append([int(s) for s in slist[k].replace('//', '/').split('/')])
  File "C:\Users\Wenhao Liu\.conda\envs\herbs4\lib\site-packages\herbs\uuuuuu.py", line 931, in <listcomp>
    face.append([int(s) for s in slist[k].replace('//', '/').split('/')])
ValueError: invalid literal for int() with base 10: ''

I used the pip to directly install the herbs in the pycharm and I tried python 3.8, 3.9, and 3.10.  I still can not solve this error.

**Comment by JingyiGF** [comment]
Hi Thanks for the report. May I know which version are you using? In PyCharm you can go to interpreter and check version for all packages.

**Comment by WenhaoLiu0218** [comment]
Hello, thank you for your reply. Here is the picture.
![image](https://user-images.githubusercontent.com/36101333/229089630-66ae374e-ec76-4e82-a3a8-acacb9d117e5.png)

**Comment by JingyiGF** [comment]
Thanks, I will check and come back to you.

**Comment by JingyiGF** [comment]
Hi, I wonder if you still get this problem?

**Comment by WenhaoLiu0218** [comment]
> Hi, I wonder if you still get this problem?

Thank you for your reply, I still get this problem. And I tried several times. So I switched to using AP_histology to track my probes.
