### ISSUE TITLE
Cannot see layers after load a proyect

### ISSUE THREAD

**Issue by Gfernandezv** [JingyiGF/HERBS#53]
Hi, I just saved a project, but every time I try to open it, the image layer doesn’t appear. The command window displays the following error:

(512, 1024, 512)
(71, 246, 653) bregma
Traceback (most recent call last):
  File "D:\Users\labpf_asus_laptop\anaconda3\envs\HERBS\lib\site-packages\herbs\herbsgui.py", line 7516, in load_project_called
    self.load_project(p_dict)
  File "D:\Users\labpf_asus_laptop\anaconda3\envs\HERBS\lib\site-packages\herbs\herbsgui.py", line 7283, in load_project
    self.load_single_image_file(
  File "D:\Users\labpf_asus_laptop\anaconda3\envs\HERBS\lib\site-packages\herbs\herbsgui.py", line 6159, in load_single_image_file
    image_file = ImageReader(image_file_path)
  File "D:\Users\labpf_asus_laptop\anaconda3\envs\HERBS\lib\site-packages\herbs\image_reader.py", line 39, in __init__
    img_data = cv2.cvtColor(img_data, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

thanks =)

**Comment by Gfernandezv** [comment]
I checked the image_reader.py script and it appears that there is a problem with the CV2 loader with jpeg files. I say this because I tried with a .tif file and had no problem.

**Comment by zguo9908** [comment]
Hi, I was wondering if this has been fixed? I also cannot see my images (jpgs) or probes when loading a project. Although the errors were slightly different. Thanks!

Traceback (most recent call last):
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 7516, in load_project_called
    self.load_project(p_dict)
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 7372, in load_project
    self.set_hist_layer_to_hist_view(
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 6970, in set_hist_layer_to_hist_view
    self.image_view.img_stacks.image_dict[layer_link].setData(
  File "C:\Users\Valued Customer\lib\site-packages\pyqtgraph\graphicsItems\ScatterPlotItem.py", line 499, in setData
    self.addPoints(*args, **kargs)
  File "C:\Users\Valued Customer\lib\site-packages\pyqtgraph\graphicsItems\ScatterPlotItem.py", line 520, in addPoints
    kargs['x'] = pos[:,0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
(1140, 1320, 800)
Traceback (most recent call last):
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 6487, in load_atlas_clicked
    self.load_volume_atlas(atlas_folder)
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 6457, in load_volume_atlas
    self.set_volume_atlas_to_view(
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 6302, in set_volume_atlas_to_view
    self.atlas_view.set_data(
  File "C:\Users\Valued Customer\lib\site-packages\herbs\atlas_view.py", line 611, in set_data
    self.label_tree.set_labels(label_info)
  File "C:\Users\Valued Customer\lib\site-packages\herbs\label_tree.py", line 102, in set_labels
    self.current_lut = np.zeros((self.label_level + 1, 4), 'i')
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 9.16 GiB for an array with shape (614454278, 4) and data type int32
Traceback (most recent call last):
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 4569, in coronal_slice_stacks_hovered
    self.atlas_view.label_tree.describe(da_id),
  File "C:\Users\Valued Customer\lib\site-packages\herbs\label_tree.py", line 219, in describe
    descr.insert(0, str(item.text(0)))
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "C:\Users\Valued Customer\lib\site-packages\herbs\herbsgui.py", line 4569, in coronal_slice_stacks_hovered
    self.atlas_view.label_tree.describe(da_id),
  File "C:\Users\Valued Customer\lib\site-packages\herbs\label_tree.py", line 219, in describe
    descr.insert(0, str(item.text(0)))
AttributeError: 'NoneType' object has no attribute 'text'
